version: "3.9"
services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: nextjs/Dockerfile
    command: npm run dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./nextjs:/nextjs
      - ./nextjs/app:/nextjs/app
      - /nextjs/node_modules
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./nextjs/app
          target: /nextjs/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json

  nest-app-1:
    container_name: nest-app-1
    build:
      context: .
      dockerfile: nest/nest-app-1/Dockerfile
      args:
        - APP=nest-app-1
    command: npm run start:dev
    restart: always
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:adminus@postgres-db:5432/postgres?schema=public"
      GOOGLE_CLIENT_ID: "test"
      GOOGLE_CLIENT_SECRET: "test"
      JWT_SECRET: "asdoasjd9348739"
      JWT_EXP: "5m"
    depends_on:
      - postgres
    volumes:
      - ./nest/nest-app-1:/nest/nest-app-1
      - /nest/nest-app-1/node_modules
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./nest/nest-app-1
          target: /nest/nest-app-1
          ignore:
            - node_modules/
        - action: rebuild
          path: ./nest/nest-app-1/package.json

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminus
      POSTGRES_DB: postgres
    ports:
      - "6543:5432" # Порт хоста 6543, порт контейнера 5432
    volumes:
      - nestjstest_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80" # Порт хоста 5555, порт контейнера 80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nestjstest_pgdata:
